---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
install:
  # Need to use the latest molecule 2.22 rc, for compatibility with ansible 2.8.x (provided in the used docker image)
  - pip install molecule==2.22rc3
  - pip install docker
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
