---
## Include tasks to idempotently create a host principal and its keytab
## Include parameters:
## - "_principal": the principal without the realm
## - "_keytab": the keytab file

- name: Create kdc principal {{ _principal }}
  command: |
    {{ kerberos_server_kadmin_cmd }} -q "addprinc -randkey {{ _principal }}@{{ kerberos_server_realm_name|upper() }}"
  register: addprinc_result
  changed_when: addprinc_result.stderr and not (addprinc_result.stderr is search("Principal or policy already exists while creating") )

- name: Fail if the principal could not be created
  fail:
    msg: The {{ _principal }} principal could not be created. Error is {{ addprinc_result.stderr }}
  when: >
    addprinc_result is failed
    or not (addprinc_result.stdout is search("Principal .* created")
    or addprinc_result.stderr is search("Principal or policy already exists while creating"))

- name: Check if keytab file exists
  stat:
    path: "{{ _keytab }}"
  register: keytab

- name: Check if principal exists in the keytab
  shell: |
    set -o pipefail;
    klist -kte {{ _keytab }} | grep -E "{{ _principal }}"
  args:
    executable: /bin/bash
  register: klist_kte_result
  changed_when: false
  failed_when: klist_kte_result.rc not in [0,1]
  when: keytab.stat.exists

- name: Create keytab with the kdcs
  command: |
    {{ kerberos_server_kadmin_cmd }} -q "ktadd -k {{ _keytab }} {{ _principal }}@{{ kerberos_server_realm_name|upper() }}"
  when: >
    not keytab.stat.exists
    or klist_kte_result.rc != 0
