---
## Note: These tasks only need to be run on the kerberos master



- block:
    - name: Create kdc host principals
      command: kadmin.local -q "addprinc -randkey  host/{{ item }}@{{ kerberos_server_realm_name|upper() }}"
      loop: "{{ kerberos_server_kdcs }}"

    - name: Create keytab with the kdcs
      command: kadmin.local -q "ktadd -k /etc/krb5.keytab host/{{ item }}@{{ kerberos_server_realm_name|upper() }}"
      loop: "{{ kerberos_server_kdcs }}"

    # Finally, we want to copy the keytab over to the slave server so that it has the keys it needs available to authenticate.
    # Done using 2 tasks (fetch + copy), because synchronize +delegate_to +'running in docker' (molecule tests) failed for me
    - name: get the keytab from the master
      fetch:
        src: /etc/krb5.keytab
        dest: /tmp/
        flat: yes
    # - name: Sync the keytab from local to the replica kdcs
    #   copy:
    #     src: /tmp/krb5.keytab
    #     dest: /etc/
    #     mode: 0644
    #   delegate_to: "{{ item }}"
    #   loop: "{{ kerberos_server_kdcs[1:] }}"

  when:
    - is_master_host

- block:
    - name: Deploy the master keytab to the replica kdcs (on replica only)
      copy:
        src: /tmp/krb5.keytab
        dest: /etc/
        mode: 0644

    - name: Deploy the kprop ACL configuration file (on replica only)
      template:
        src: kpropd.acl.j2
        dest: /var/kerberos/krb5kdc/kpropd.acl
      notify:
        - restart kprop

    - name: Start the kprop service (on replica only)
      service:
        name: "{{ kerberos_kprop_service }}"
        state: started
        enabled: True
  when:
    - is_replica_host

- name: Deploy the kprop replication script
  template:
    src: kprop_kdc_replica_sync.sh
    dest: /var/kerberos/kprop_kdc_replica_sync.sh
    mode: 0755
  when:
    - is_master_host

- block:
    - name: ensure cron is installed
      package:
        name: cronie

    - name: ensure crond service enabled and started
      service:
        name: crond
        state: started
        enabled: yes

    - name: Deploy kprop cronjob (only required with replicas)
      cron:
        name: "Sync Master KDC with Replica every 5 minutes"
        minute: "*/5"
        job: "/var/kerberos/kprop_kdc_replica_sync.sh"
  when:
    - kerberos_server_kprop_cronjob_enabled
    - is_master_host
